-- CreateTable
CREATE TABLE "UserGoal" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "dailyIntake" INTEGER NOT NULL DEFAULT 2000,
    "dailyBurn" INTEGER NOT NULL DEFAULT 500,
    "dailyWater" INTEGER NOT NULL DEFAULT 8
);
