export const AUTHORITATIVE_FOODS = [
  { name: '白米饭', emoji: '🍚', calories: 116, unit: '100g', source: 'USDA' },
  { name: '白面条', emoji: '🍜', calories: 109, unit: '100g', source: 'USDA' },
  { name: '全麦面包', emoji: '🍞', calories: 247, unit: '100g', source: 'USDA' },
  { name: '燕麦片', emoji: '🥣', calories: 389, unit: '100g', source: 'USDA' },
  { name: '鸡胸肉（水煮）', emoji: '🍗', calories: 165, unit: '100g', source: 'USDA' },
  { name: '瘦牛肉', emoji: '🥩', calories: 250, unit: '100g', source: 'USDA' },
  { name: '瘦猪肉', emoji: '🥓', calories: 143, unit: '100g', source: 'USDA' },
  { name: '三文鱼', emoji: '🐟', calories: 208, unit: '100g', source: 'USDA' },
  { name: '鸡蛋', emoji: '🥚', calories: 155, unit: '100g', source: 'USDA' },
  { name: '西兰花', emoji: '🥦', calories: 34, unit: '100g', source: 'USDA' },
  { name: '菠菜', emoji: '🥬', calories: 23, unit: '100g', source: 'USDA' },
  { name: '胡萝卜', emoji: '🥕', calories: 41, unit: '100g', source: 'USDA' },
  { name: '番茄', emoji: '🍅', calories: 18, unit: '100g', source: 'USDA' },
  { name: '黄瓜', emoji: '🥒', calories: 16, unit: '100g', source: 'USDA' },
  { name: '苹果', emoji: '🍎', calories: 52, unit: '100g', source: 'USDA' },
  { name: '香蕉', emoji: '🍌', calories: 89, unit: '100g', source: 'USDA' },
  { name: '橙子', emoji: '🍊', calories: 47, unit: '100g', source: 'USDA' },
  { name: '草莓', emoji: '🍓', calories: 32, unit: '100g', source: 'USDA' },
  { name: '蓝莓', emoji: '🫐', calories: 57, unit: '100g', source: 'USDA' },
  { name: '巨无霸汉堡', emoji: '🍔', calories: 550, unit: '个', source: 'McDonald\'s' },
  { name: '薯条（中份）', emoji: '🍟', calories: 320, unit: '份', source: 'McDonald\'s' },
  { name: '可乐（330ml）', emoji: '🥤', calories: 139, unit: '罐', source: 'USDA' },
  { name: '披萨（1片）', emoji: '🍕', calories: 285, unit: '片', source: 'USDA' },
  { name: '甜甜圈', emoji: '🍩', calories: 452, unit: '个', source: 'USDA' },
  { name: '巧克力（100g）', emoji: '🍫', calories: 546, unit: '100g', source: 'USDA' },
  { name: '全脂牛奶', emoji: '🥛', calories: 61, unit: '100ml', source: 'USDA' },
  { name: '低脂酸奶', emoji: '🥤', calories: 59, unit: '100g', source: 'USDA' },
  { name: '奶酪', emoji: '🧀', calories: 402, unit: '100g', source: 'USDA' },
  { name: '杏仁', emoji: '🥜', calories: 579, unit: '100g', source: 'USDA' },
  { name: '核桃', emoji: '🌰', calories: 654, unit: '100g', source: 'USDA' },
  { name: '花生', emoji: '🥜', calories: 567, unit: '100g', source: 'USDA' },
];

export const AUTHORITATIVE_EXERCISES = [
  { name: '静坐/看电视', emoji: '🛋️', met: 1.0, intensity: '极低', source: 'Compendium' },
  { name: '使用电脑/办公', emoji: '💻', met: 1.5, intensity: '极低', source: 'Compendium' },
  { name: '站立（轻松）', emoji: '🧍', met: 1.8, intensity: '极低', source: 'Compendium' },
  { name: '慢走（2.5 km/h）', emoji: '🚶', met: 2.3, intensity: '低', source: 'Compendium' },
  { name: '瑜伽（哈他瑜伽）', emoji: '🧘', met: 2.5, intensity: '低', source: 'Compendium' },
  { name: '快走（4.5 km/h）', emoji: '🚶', met: 3.5, intensity: '中等', source: 'Compendium' },
  { name: '骑自行车（轻松）', emoji: '🚴', met: 4.0, intensity: '中等', source: 'Compendium' },
  { name: '太极拳', emoji: '🥋', met: 4.0, intensity: '中等', source: 'Compendium' },
  { name: '跳舞（交谊舞）', emoji: '💃', met: 4.8, intensity: '中等', source: 'Compendium' },
  { name: '力量训练（中等）', emoji: '🏋️', met: 5.0, intensity: '中等', source: 'Compendium' },
  { name: '游泳（慢速）', emoji: '🏊', met: 5.8, intensity: '中等', source: 'Compendium' },
  { name: '慢跑（6.4 km/h）', emoji: '🏃', met: 6.0, intensity: '高', source: 'Compendium' },
  { name: '快走（6.4 km/h）', emoji: '🚶', met: 6.3, intensity: '高', source: 'Compendium' },
  { name: '骑自行车（中等）', emoji: '🚴', met: 6.8, intensity: '高', source: 'Compendium' },
  { name: '篮球（非比赛）', emoji: '🏀', met: 6.5, intensity: '高', source: 'Compendium' },
  { name: '网球（双打）', emoji: '🎾', met: 5.0, intensity: '中等', source: 'Compendium' },
  { name: '网球（单打）', emoji: '🎾', met: 8.0, intensity: '高', source: 'Compendium' },
  { name: '跑步（8 km/h）', emoji: '🏃', met: 8.3, intensity: '高', source: 'Compendium' },
  { name: '游泳（中等速度）', emoji: '🏊', met: 7.0, intensity: '高', source: 'Compendium' },
  { name: '跑步（9.7 km/h）', emoji: '🏃', met: 9.8, intensity: '极高', source: 'Compendium' },
  { name: '跑步（12 km/h）', emoji: '🏃', met: 11.5, intensity: '极高', source: 'Compendium' },
  { name: '快速骑自行车', emoji: '🚴', met: 10.0, intensity: '极高', source: 'Compendium' },
  { name: '高强度间歇训练', emoji: '🔥', met: 11.0, intensity: '极高', source: 'Compendium' },
  { name: '篮球（比赛）', emoji: '🏀', met: 8.0, intensity: '高', source: 'Compendium' },
  { name: '足球（比赛）', emoji: '⚽', met: 10.0, intensity: '极高', source: 'Compendium' },
  { name: '跳绳（快速）', emoji: '🪢', met: 12.3, intensity: '极高', source: 'Compendium' },
  { name: '游泳（快速）', emoji: '🏊', met: 9.8, intensity: '极高', source: 'Compendium' },
];

export default {
  foods: AUTHORITATIVE_FOODS,
  exercises: AUTHORITATIVE_EXERCISES,
};

